CarRental/CarRental.Web/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRental.BLL.Entities;
using CarRental.Services.Interfaces;
using CarRental.ViewModels.ManageViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarRental.Web.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICarsService _carsService;

        public CarsController(ICarsService carsService)
        {
            _carsService = carsService;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            var model = _carsService.GetCar();
            
            return View(model);
        }
        [HttpGet]
        public IActionResult GetCar(int Id)
        {
           var model = _carsService.GetCar(Id);

            return View(model);
        }
        [HttpGet]
        public IActionResult AddCar()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddCar(Cars car)
        {
            _carsService.AddCar(car);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditCar(int id)
        {
            var model = _carsService.GetCar(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult EditCar( Cars car, int id)
        {
            _carsService.EditCar(car,id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult DeleteCar()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult DeleteCar( int id)
        {
            _carsService.DeleteCar(id);
            return RedirectToAction("Index");
        }

        public IActionResult CarRent()
        {
            return View();
        }
    }
}

CarRental/CarRental.Web/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRental.BLL.Entities;
using CarRental.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CarRental.Web.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ICustomersService _customersService;

        public CustomersController(ICustomersService customersService)
        {
            this._customersService = customersService;
        }

        public IActionResult Index()
        {
            var model = _customersService.GetCustomer();

            return View(model);
        }

        [HttpGet]
        public IActionResult AddCustomer()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCustomer(Customers customer)
        {
            _customersService.AddCustomer(customer);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditCustomer(int id)
        {
            var model = _customersService.GetCustomer(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult EditCustomer(int id, Customers customer)
        {
            _customersService.EditCustomer(customer, id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult DeleteCustomer()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult DeleteCustomer(int id)
        {
            _customersService.DeleteCustomer(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult GetCustomer (int Id)
        {
            var model = _customersService.GetCustomer(Id);

            return View(model);
        }

    }
}

CarRental/CarRental.Web/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRental.BLL.Entities;
using CarRental.Services.Interfaces;
using CarRental.ViewModels.ManageViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CarRental.Web.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrdersService _ordersService;
        

      
        public OrdersController(IOrdersService ordersService )
        {
            this._ordersService = ordersService;
            
        }
        public IActionResult Index()
        {
            OrdersViewModel model = new OrdersViewModel() {
                OrderList = _ordersService.GetOrder()
        };
         
            return View(model);
        }
        [HttpGet]
        public IActionResult GetOrder(int Id)
        {
            var model = new OrdersViewModel();
            model.Order=_ordersService.GetOrder(Id);
            model.Cust = _ordersService.GetCustomer(model.Order.CustId);
            

            return View(model);
        }
        
            
        
        [HttpGet]
        public IActionResult AddOrder()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddOrder(Orders order)
        {
            _ordersService.AddOrder(order);
            return RedirectToAction("Index");
        }

       
      

        [HttpGet]
        public IActionResult EditOrder(int id)
        {
            var model = new OrdersViewModel(); 
              model.Order = _ordersService.GetOrder(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult EditOrder(Orders order, int id)
        {
            _ordersService.EditOrder(order, id);
            return RedirectToAction("Index");
        }

        
       
       

        [HttpGet]
        public ActionResult DeleteOrder()
        {
            return View();
        }
        //[HttpPost]
        public IActionResult DeleteOrder(int id)
        {
            _ordersService.DeleteOrder(id);
            return RedirectToAction("Index");
        }
        
        public ActionResult OrderInfo()
        {
            return View();
        }
        [HttpGet]
        public ActionResult OrderInfoView(string ServiceNo)
        {
            var model = new OrdersViewModel();
            model.Order = _ordersService.GetOrderByNo(ServiceNo);
            return PartialView("szukaj", model);
        }
    }
}

CarRental/CarRental.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<CarRental.BLL.Entities.User> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Setup Solution</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <environment include="Development">
        <link rel="stylesheet" href="~/css/StyleSheet.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />

    </environment>
  
       
</head>
<body>

    
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Shine of Divine</a>
            </div>
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Śledzenie naprawy", "OrderInfo", "Orders")</li>
                <li>  @Html.ActionLink("Likwidacja szkód", "LikwidacjaSzkod", "Home")</li>
                <li> @Html.ActionLink("Pomoc drogowa", "PomocDrogowa", "Home")</li>



                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Naprawy
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Blacharsko-lakiernicze", "BlachLak", "Home")</li>
                        <li>@Html.ActionLink("Mechaniczne", "Mechaniczne", "Home")</li>

                    </ul>
                </li>
                <li>@Html.ActionLink("Wypożyczalnia", "CarRent", "Cars")</li>
                <li>@Html.ActionLink("O nas", "About", "Home")</li>
                <li>@Html.ActionLink("Galeria", "Gallery", "Home")</li>
                <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                @await Html.PartialAsync("_LoginPartial")
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Menu
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Samochody", "Index", "Cars")</li>
                            <li>@Html.ActionLink("Klienci", "Index", "Customers")</li>
                            <li>@Html.ActionLink("Naprawy", "Index", "Orders")</li>
                        </ul>
                    </li>
                }
            </ul>
        </div>
        </nav>
        
        <br />
        <div class="container body-content">
            @RenderBody()
        </div>
        <hr />

        <footer>

            <div class="container second-portion">
                <div class="row">
                    <!-- Boxes de Acoes -->
                    <div class="col-xs-12 col-sm-6 col-lg-4">
                        <div class="box">
                            <div class="icon">
                                <div class="image"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
                                <div class="info">
                                    <h3 class="title">Godziny otwarcia</h3>
                                    <p>
                                        Pn-Pt: 8-18


                                    </p>
                                    <p>
                                        Pomoc drogowa 24h
                                        <br>

                                    </p>
                                </div>
                            </div>
                            <div class="space"></div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-lg-4">
                        <div class="box">
                            <div class="icon">
                                <div class="image"><i class="fa fa-mobile" aria-hidden="true"></i></div>
                                <div class="info">
                                    <h3 class="title">Kontakt</h3>
                                    <p>
                                        <i class="fa fa-mobile" aria-hidden="true"></i> &nbsp  509 917 889
                                        <br>
                                        <i class="fa fa-mobile" aria-hidden="true"></i> &nbsp  507 100 381
                                        <br>
                                        <i class="fa fa-mobile" aria-hidden="true"></i> &nbsp  515 958 945
                                        <br>

                                    </p>
                                    <p>
                                        <i class="fa fa-envelope" aria-hidden="true"></i> &nbsp shineofdivine@gmail.com
                                        <br>

                                    </p>
                                </div>
                            </div>
                            <div class="space"></div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-lg-4">
                        <div class="box">
                            <div class="icon">
                                <div class="image"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
                                <div class="info">
                                    <h3 class="title">Adres</h3>
                                    <p>
                                        <i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp Lisia 20B, 05-270 Marki.
                                    </p>
                                </div>
                            </div>
                            <div class="space"></div>
                        </div>
                    </div>
                </div>
            </div>
            <p>&copy; 2019 - Wojciech Sowa</p>
        </footer>



        @RenderSection("Scripts", required: false)
</body>
</html>